[package]
name = "simple_injector"
version = "0.1.0"
authors = ["Dennis Kievits <denkievits@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elertan_cheat_base = { path = "../.." }
sysinfo = "0.15.3"
